# Generated by Django 5.0.6 on 2024-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCard', models.IntegerField()),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.TextField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
